# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_cards',
                'doc_host': 'https://manuflexor.github.io',
                'git_url': 'https://github.com/manuflexor/nbdev_cards',
                'lib_path': 'nbdev_cards'},
  'syms': { 'nbdev_cards.card': { "nbdev_cards.card.'Card'.__eq__": ("card.html#'card'.__eq__", 'nbdev_cards/card.py'),
                                  "nbdev_cards.card.'Card'.__lt__": ("card.html#'card'.__lt__", 'nbdev_cards/card.py'),
                                  'nbdev_cards.card.Card': ('card.html#card', 'nbdev_cards/card.py'),
                                  'nbdev_cards.card.Card.__eq__': ('card.html#card.__eq__', 'nbdev_cards/card.py'),
                                  'nbdev_cards.card.Card.__init__': ('card.html#card.__init__', 'nbdev_cards/card.py'),
                                  'nbdev_cards.card.Card.__str__': ('card.html#card.__str__', 'nbdev_cards/card.py')},
            'nbdev_cards.deck': { 'nbdev_cards.deck.Card': ('deck.html#card', 'nbdev_cards/deck.py'),
                                  'nbdev_cards.deck.Card.__eq__': ('deck.html#card.__eq__', 'nbdev_cards/deck.py'),
                                  'nbdev_cards.deck.Card.__init__': ('deck.html#card.__init__', 'nbdev_cards/deck.py'),
                                  'nbdev_cards.deck.Card.__str__': ('deck.html#card.__str__', 'nbdev_cards/deck.py')}}}