# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_card.ipynb.

# %% auto 0
__all__ = ['Card']

# %% ../00_card.ipynb 7
class Card:
    "A playing card"
    def __init__(self,
                 suit: int, # An index into `suits`
                 rank: int): # An index into `ranks`
        self.suit = suit
        self.rank = rank
    def __str__(self): #stringfy my object
        return f'{ranks[self.rank]}{suits[self.suit]}'
    __repr__ = __str__ 
    def __eq__(self, a: 'Card'):
        return (self.suit, self.rank)==(a.suit, a.rank)

# %% ../00_card.ipynb 12
@patch
def __eq__(self: 'Card', a: 'Card'):
    return (self.suit, self.rank)==(a.suit, a.rank)

# %% ../00_card.ipynb 14
@patch
def __lt__(self: 'Card', a: 'Card'):
        return (self.suit, self.rank)<(a.suit, a.rank)
